# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2746555b41acc293ca59fa1deecf0de9dbe67914fe485c77760d31d567b067b7e58b9ca4d6b0a547052998a19f0a77c6f2609c6f54d2a56013a7738fb80c4853

test:
  secret_key_base: 6218c6525bbfbda537c57d547d44628b5abbc7faf1ff8c069c087cd27c7d5e18fa44037830f3cfc38377c183d7e9ea810602643a852225576225ca3b2b8d9c2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
